name: dio_proxy_plugin_example
description: Demonstrates how to use the dio_proxy_plugin plugin.
publish_to: none
environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.12.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  dio_proxy_plugin:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
